language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7
script: phpunit TPSTest Tests/public/lib/tpsTest.php
script: phpunit TPSTest Tests/public/lib/genreTest.php


before_script:
    - composer install --no-dev
    
